#!/usr/bin/env node
/* ============================================================
   build-library.mjs — bundle library/*.json into library/library.js

   Drop an exported IC (⬇ Export ICs) into library/ and run:

       node tools/build-library.mjs

   Why a bundle rather than reading the folder at startup: Logic Lab is
   meant to run by opening index.html directly, and a file:// page cannot
   fetch a sibling file — Chrome blocks it as a cross-origin request, and
   no browser can list a directory anyway. A <script> tag *does* load from
   file://, so the library ships as one generated script that works both
   locally and on the deployed site. The .json files stay the source of
   truth; this only re-derives the bundle from them.
   ============================================================ */

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = process.argv[2] ? process.argv[2] : join(root, "library");   // overridable for tests
const out = join(dir, "library.js");

if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

const files = readdirSync(dir).filter(f => f.toLowerCase().endsWith(".json")).sort();
const defs = [];
const seen = new Map();
let skipped = 0;

for (const f of files) {
  let data;
  try {
    data = JSON.parse(readFileSync(join(dir, f), "utf8"));
  } catch (err) {
    console.error(`  !  ${f}: not valid JSON — ${err.message}`);
    skipped++;
    continue;
  }
  // component exports and sketch exports both carry a `defs` array; a sketch's
  // sheet is ignored here, only the components it bundles are library material
  const list = Array.isArray(data && data.defs) ? data.defs : null;
  if (!list) {
    console.error(`  !  ${f}: no "defs" array — is this a Logic Lab export?`);
    skipped++;
    continue;
  }
  let took = 0;
  for (const d of list) {
    if (!d || !d.name || !d.circuit || !d.inputs || !d.outputs) {
      console.error(`  !  ${f}: skipping a malformed component`);
      continue;
    }
    if (seen.has(d.name)) {
      if (seen.get(d.name) !== f)
        console.error(`  !  ${f}: "${d.name}" already came from ${seen.get(d.name)} — keeping the first`);
      continue;
    }
    seen.set(d.name, f);
    defs.push({ name: d.name, short: d.short || d.name, circuit: d.circuit, inputs: d.inputs, outputs: d.outputs });
    took++;
  }
  console.log(`  ✓  ${f} — ${took} component${took === 1 ? "" : "s"}`);
}

const body = `/* GENERATED by tools/build-library.mjs — do not edit by hand.
   Source: library/*.json (${files.length} file${files.length === 1 ? "" : "s"}).
   Re-run "node tools/build-library.mjs" after adding or removing one. */
window.LOGIC_LAB_LIBRARY = ${JSON.stringify({ version: 1, defs })};
`;
writeFileSync(out, body);

console.log(`\n${defs.length} component${defs.length === 1 ? "" : "s"} from ${files.length - skipped} file${files.length - skipped === 1 ? "" : "s"} → ${basename(out)}`);
if (!defs.length) console.log("(library/ is empty — drop an exported .json in and run this again)");
